### ISSUE TITLE
Meta tags goodies

### ISSUE THREAD

**Issue by marionzualo** [marionzualo/gfaa#7]
- [x] Add open graph thingies
- [x] Add title and description thingies
- [x] Add twitter cards

**Comment by pedrocarrico** [comment]
May I suggest [Twitter cards](https://dev.twitter.com/cards/overview) also?

**Comment by marionzualo** [comment]
@pedrocarrico will do that as well! Thanks for the heads up
BTW: http://www.goodfuckingausterityadvice.com/
